#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
    echo ${red}"This program must be run as root ${textreset}"
    echo "Exiting"
    exit
else
    echo "Running Program"
fi

items=(1 "User/Group Management"
       2 "DNS Management"
)

while choice=$(dialog --title "$TITLE" \
    --backtitle "Active Directory Management" \
    --menu "Please select" 25 40 3 "${items[@]}" \
    2>&1 >/dev/tty); do
    case $choice in
    1) /root/.servman/ADManUser ;;
    2) /root/.servman/ADManNS ;;
    esac
done
clear # clear after user pressed Cancel
