#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
    echo ${red}"This program must be run as root ${textreset}"
    echo "Exiting"
    exit
else
    echo "Running Program"
fi

items=(1 "Add User"
    2 "Delete User"
    3 "Password Reset"
    4 "Enable/Disable User"
    5 "List All Users"
    6 "Create New Group"
    7 "Delete Group"
    8 "List Groups"
    9 "Add User to Group"
   10 "Remove User from Group"
)

while choice=$(dialog --title "$TITLE" \
    --backtitle "Active Directory Management --> User Management" \
    --menu "Please select" 25 40 3 "${items[@]}" \
    2>&1 >/dev/tty); do
    case $choice in
    1) /root/.servman/ADManager/adduser.sh ;;
    2) /root/.servman/ADManager/deleteuser.sh ;;
    3) /root/.servman/ADManager/pass-reset ;;
    4) /root/.servman/ADManager/enable_disable.sh ;;
    5) /root/.servman/ADManager/list-all-users ;;
    6) /root/.servman/ADManager/create-new-group ;;
    7) /root/.servman/ADManager/delete-group ;;
    8) /root/.servman/ADManager/list-group ;;
    9) /root/.servman/ADManager/mv-user-to-group ;;
   10) /root/.servman/ADManager/rm-user-frm-group ;;
    esac
done
clear # clear after user pressed Cancel
