#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
    echo ${red}"This program must be run as root ${textreset}"
    echo "Exiting"
    exit
else
    echo "Running Program"
fi

items=(1 "Create new DHCP Scope"
    2 "List DHCP Leases"
    3 "Query DHCP Database"
    4 "Start DHCP Server"
    5 "Stop DHCP Server"
    6 "Restart DHCP Service"
    7 "Enable DHCP Server Service"
    8 "Disable DHCP Service"
    9 "DHCP Server Status"
   10 "Edit DHCP Config Manually"
)

while choice=$(dialog --title "$TITLE" \
    --backtitle "DHCP Server Management" \
    --menu "Please select" 20 40 3 "${items[@]}" \
    2>&1 >/dev/tty); do
    case $choice in
    1) /root/.servman/DHCPManager/DHCPcreatescope ;;
    2) /root/.servman/DHCPManager/DHCPlist ;;
    3)  /root/.servman/DHCPManager/dhcp-query ;;
    4) /root/.servman/DHCPManager/DHCPstart ;;
    5) /root/.servman/DHCPManager/DHCPstop ;;
    6) /root/.servman/DHCPManager/DHCPrestart ;;
    7) /root/.servman/DHCPManager/DHCPenable ;;
    8) /root/.servman/DHCPManager/DHCPdisable ;;
    9) /root/.servman/DHCPManager/DHCPstatus ;;
   10) /root/.servman/DHCPManager/DHCPeditconfig ;;
    esac
done
clear # clear after user pressed Cancel
