#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi

items=(1 "Enable SM on Boot"
       2 "Disable SM on Boot"
       3 "Update Module"
)

while choice=$(dialog --title "$TITLE" \
		 --backtitle "System Management" \
                 --menu "Please select" 20 40 3 "${items[@]}" \
                 2>&1 >/dev/tty)
    do
    case $choice in
        1) /root/.servman/ServerManager/sm-enable;; 
        2) /root/.servman/ServerManager/sm-disable;;
	3) /root/.servman/ServerManager/update-server-manager;;
    esac
done
clear # clear after user pressed Cancel
