#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi

items=(1 "Configure Network"
       2 "Show Network Settings"
       3 "Reboot the Server"
       4 "Shutdown the Server")

while choice=$(dialog --title "$TITLE" \
                 --backtitle "System Management" \
                 --menu "Please select" 20 40 3 "${items[@]}" \
                 2>&1 >/dev/tty)
    do
    case $choice in
        1) /root/.servman/SystemManager/configure-network ;;
        2) /root/.servman/SystemManager/show-network;;
        3) /root/.servman/SystemManager/reboot-server;;
        4) /root/.servman/SystemManager/shutdown-server;;
    esac
done
clear # clear after user pressed Cancel
