#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
   echo " "
else
   echo ${RED}"This program must be run as root ${TEXTRESET}"
   echo "Exiting"
fi
clear
cat <<EOF
${GREEN}Server Management${TEXTRESET}
${GREEN}Remove Server Management On-Boot${TEXTRESET}


You are removing System Management from autmotcially starting when logging in as root.
You can still start SM-GUI at any time by typing ${YELLOW}server-manager${TEXTRESET} in the CLI.

EOF

while true; do
   read -p "Do you want to disable SM on Boot? (y/n) " yn
   case $yn in
   [yY])
      sed -i '/server-manager/d' /root/.bash_profile
      echo ${RED}"Removed the Entry${TEXTRESET}"
      sleep 1
      break
      ;;
   [nN])
      echo ${RED}"Cancelled${TEXTRESET}"
      sleep 1
      exit
      ;;
   *) echo invalid response ;;
   esac
done
exit
