#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

cat <<EOF
${yellow}System Management on Boot${textreset}

EOF

while true; do
read -p "Do you want to enable SM on Boot? (y/n) " yn
case $yn in
   [yY] ) echo "/usr/bin/server-manager" >> /root/.bash_profile;
      break;;
   [nN] ) echo exiting...;
      exit;;
   * ) echo invalid response;;
esac
done
exit
