#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}System Management${TEXTRESET}
${GREEN}System Management On-Boot${TEXTRESET}
EOF


while true; do
read -p "Do you want to enable System Management GUI Automatically? (y/n) " yn
case $yn in
   [yY] ) echo "/usr/bin/server-manager" >> /root/.bash_profile;
      break;;
   [nN] ) echo exiting...;
      exit;;
   * ) echo invalid response;;
esac
done
exit
