#!/bin/bash

# --- Color setup ---
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)

# --- Check root ---
USER=$(whoami)
if [ "$USER" != "root" ]; then
    echo "${RED}This program must be run as root${TEXTRESET}"
    echo "Exiting"
    exit 1
fi

# --- Temporary file ---
TMP_FILE=$(mktemp)
trap 'rm -f "$TMP_FILE"' EXIT

# --- Clear screen ---
clear

# --- Fetch nmcli info ---
nmcli > "$TMP_FILE" 2>&1

# --- Show dialog textbox ---
dialog --backtitle "Network Settings" \
       --title "nmcli Network Overview" \
       --textbox "$TMP_FILE" 35 80
