#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}System Management${TEXTRESET}
${GREEN}Shutdown Server${TEXTRESET}
EOF

cat <<EOF
This will ${RED}SHUTDOWN${TEXTESET} the system now
EOF
while true; do
   read -p "Do you want to proceed? (y/n) " yn
   case $yn in
   [yY])
      echo ${RED}"Powering Off${TEXTRESET}"
      sleep 1
      shutdown -h now
      break
      ;;
   [nN])
      echo ${RED}"Cancelled${TEXTRESET}"
      exit
      ;;
   *) echo invalid response ;;
   esac
done
