#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
   echo ${red}"This program must be run as root ${textreset}"
   echo "Exiting"
   exit
else
   echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear

cat <<EOF
This will ${red}SHUTDOWN${textreset} the system now
You will have to physically power on the system
EOF
while true; do
   read -p "Do you want to proceed? (y/n) " yn
   case $yn in
   [yY])
      reboot
      break
      ;;
   [nN])
      echo exiting...
      exit
      ;;
   *) echo invalid response ;;
   esac
done
