#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
    echo ${red}"This program must be run as root ${textreset}"
    echo "Exiting"
    exit
else
    echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear

cat <<EOF
Create An AD User:
Please provide the following information to create a new user in Active Directory
EOF

read -p "Please provide the First Name for the User : " FIRSTNAME
read -p "Please provide the Last Name for the User: " LASTNAME
read -p "Please provide the Initials for the User: " INITIALS
read -p "Please provdie the login account name for the user : " LOGINNAME

cat <<EOF
Adding the following:
Login Name: ${green}$USER${textreset}
First Name: ${green}$FIRSTNAME${textreset}
Last Name: ${green}$LASTNAME${textreset}
Initials: ${green}$INITIALS${textreset}
EOF

samba-tool user add $LOGINNAME --given-name $FIRSTNAME --surname $LASTNAME --initials $INITIALS

echo ${green}"Current user List${textreset}"
echo " "
samba-tool user list
echo " "
read -p "Press Any Key"
