#!/bin/bash
#Checking for user permissions
SERVER=$(hostname)
user=$(whoami)
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear

cat <<EOF
${green}Delete a forward Zone:${textreset}

EOF

samba-tool dns zonelist $SERVER -U Administrator
 
read -p ${yellow}"From the list, please input the zone you wish to delete:${textreset} " ZONE

samba-tool dns zonedelete $SERVER $ZONE -UAdministrator

read -p ${yellow}"Press Any Key${textreset}"

clear

echo "Here is the updated Zone information:"

samba-tool dns zonelist $SERVER -U Administrator

read -p "Press Any Key"
