#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
    echo ${red}"This program must be run as root ${textreset}"
    echo "Exiting"
    exit
else
    echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear

cat <<EOF
Delete An AD User:

EOF

echo " "
samba-tool user list
echo " "
read -p "From the list, please input the user you want to delete : " LOGINNAME

samba-tool user delete $LOGINNAME

echo "Current user List"

samba-tool user list

read -p "Press Any Key"
