#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}Create Forward Zone${TEXTRESET}


EOF
read -p "Please provide the name (i.e. newzone.int) for the new forward Zone: " ZONE

samba-tool dns zonecreate $SERVER $ZONE -UAdministrator

read -p ${yellow}"Press Any Key${textreset}"

clear

echo "Updated Zone information:"

samba-tool dns zonelist $SERVER -U Administrator
