#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)
FQDN=$(hostname)
DOMAIN=$(hostname | sed 's/^[^.:]*[.:]//')


#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}DNS Create New Reverse Zone${TEXTRESET}
EOF


read -p "Please provide the reverse zone address you would like to create(i.e. 192.168.24): " ZONE


REVERSE=$(echo "$ZONE" | {
  IFS=. read q1 q2 q3 q4
  echo "$q3.$q2.$q1"
})

samba-tool dns zonecreate ${FQDN} ${REVERSE}.in-addr.arpa -U Administrator

echo "Listing Zones"

sleep 1

samba-tool dns zonelist ${FQDN} -U Administrator

sleep 3
