#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}Create New Group${TEXTRESET}
EOF

read -p "Please provide the Name of the group to create : " "GROUPNAME"

samba-tool group add "$GROUPNAME"

echo ${GREEN}"Current Group List${TEXTRESET}"
cat  << EOF

EOF
samba-tool group list | column -c 100
cat << EOF
   
EOF
read -p "Press Any Key"
