#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
  echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat <<EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}Delete a Group ${TEXTRESET}

EOF
samba-tool group list | column -c 100
read -p "Please provide the Name of the group to delete : " GROUPNAME

samba-tool group delete "${GROUPNAME}"

echo ${GREEN}"Current Group List${TEXTRESET}"
echo " "
samba-tool group list | column -c 100
echo " "
read -p "Press Any Key"
