#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
  echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat <<EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}Enable USer${TEXTRESET}

EOF

samba-tool user list
echo " "
read -p "From the list, please provide the account you want to enable : " LOGINNAME


samba-tool user enable $LOGINNAME

cat <<EOF
${GREEN}User Status${TEXTRESET}

EOF

samba-tool user show $LOGINNAME


read -p "Press Enter"
