#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
  echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat <<EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}Move a User to Group${TEXTRESET}
EOF

samba-tool group list | column -c 100
read -p "Please provide the Name of the group to use : " GROUPNAME

clear

samba-tool user list | column -c 100

read -p "Please provide the user you want to add to the group: " ADUSER

samba-tool group addmembers "$GROUPNAME" "$ADUSER"

echo " "
echo ${GREEN}"This is the users updated Group Membership:${TEXTRESET}"
samba-tool user show $ADUSER | grep memberOf:
echo ${GREEN}"This is the Groups Members${TEXTRESET}"
samba-tool group show "$GROUPNAME"
read -p "Press Any Key"
