#!/bin/bash
#AD Passowrd Reset
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
  echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat <<EOF
${GREEN}Active Directory Management${TEXTRESET}
${GREEN}User Password Reset${TEXTRESET}

EOF

samba-tool user list
echo " "
read -p "From the list, please input the user of whom you want to reset their password: " LOGINNAME

samba-tool user setpassword $LOGINNAME

read -p "Press Any Key"
