#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear


echo "Please provide the following information to create a new scope for DHCP:"


read -p "Please provide the Network SUBNET to create (i.e. 192.168.25.0): " SUBNETNETWORK
read -p "Please provide the Network MASK to create (i.e. 255.255.255.0): " DHCPNETMASK 
read -p "Please provide the beginning IP address in the lease range: " DHCPBEGIP
read -p "Please provdie the ending IP address in the lease range: " DHCPENDIP
read -p "Please provide the default gateway for clients: " DHCPDEFGW
read -p "Please provide a description for this subnet: " SUBNETDESC




cat <<EOF > /root/.servman/DHCPManager/dhcp.tmp

#$SUBNETDESC
subnet $SUBNETNETWORK netmask $DHCPNETMASK {
        range $DHCPBEGIP $DHCPENDIP;
        option routers $DHCPDEFGW;
}
EOF

cat /root/.servman/DHCPManager/dhcp.tmp >> /etc/dhcp/dhcpd.conf
rm -f /root/.servman/DHCPManager/dhcp.tmp

echo "The new configuration has been applied to dhcpd.conf"
more /etc/dhcp/dhcpd.conf



while true; do
read -p "Would you like to restart the DHCP service now? (y/n) " yn
case $yn in 
   [yY] ) systemctl restart dhcpd;
      break;;
   [nN] ) echo exiting...;
      exit;;
   * ) echo invalid response;;
esac
done
exit

read -p "Press Any Key"

