#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear
cat  <<EOF
${green}Starting DHCP${textreset} Service
EOF
systemctl start dhcpd
ps -ax | grep dhcpd | head 
sleep 1 

cat <<EOF
Checking Status 
EOF
 

systemctl status dhcpd

read -p "Press Any Key"

