#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}Samba Server Management${TEXTRESET}
${GREEN}Restart Samba Server${TEXTRESET}
EOF


systemctl restart samba

echo ${YELLOW}"*To exit the Next Screen press the "q" key${TEXTRESET}"
read -p "Press Any Key"
systemctl status samba
