#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}Samba Server Management${TEXTRESET}
${GREEN}Samba Service DNF Update Log${TEXTRESET}
EOF


more /var/log/dnf-smb-mon.log

read -p "Press Any Key"
