#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)
#In the event a samba update arrives from Rocky Linux, rebuild Samba packages
dnflocal=$(dnf provides samba | grep Provide | sed 's/.dc//' | sed '1d')
dnfremote=$(dnf provides samba | grep Provide | sed 's/.dc//' | sed '$d')
mocksmbver=$(dnf provides samba | grep samba | sed '2,4d' | cut -d: -f1 | cut -dx -f1)
majoros=$(cat /etc/redhat-release | grep -Eo "[0-9]" | sed '$d')
minoros=$(cat /etc/redhat-release | grep -Eo "[0-9]" | sed '1d')

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}Samba Server Management${TEXTRESET}
${GREEN}Samba Mock Update${TEXTRESET}
EOF
clear
cat <<EOF
This script will update your Samba binary packages to the latest version as prescribed from the upstream Rocky Provider
It's suggested that you schedule downtime for this as the sources will need to rebuild
It's suggested that you ${YELLOW}REBOOT${TEXTRESET} after the update

Keep in mind you SHOULD NOT be running this command unless you receieved a notification when you logged
in that there was a change in .scr.rpm. OR you saw in the Samba dnf replication logs that repositories were NOT in sync
EOF

cat <<EOF
This Utility is going to update your compiled Samba version to a newer version

The current local version on the system is:
$dnflocal

And the Version in the upstream repository is:
$dnfremote

EOF

echo ${YELLOW}"The Last log entry for the Smaba replication log is:${TEXTRESET}"
tail -1 /var/log/dnf-smb-mon.log
echo " "

cat <<EOF
This process will:
        -Remove local packages
        -Download the new samba source
        -Use mock to compile the source rpm
        -Recreate the repo in the same location
        -Run dnf update to the new version of Samba, with dependencies
EOF
while true; do

   read -p "Would you like to update the system now? (y/n) " yn

   case $yn in
   [yY])
      # delete all packages
      rm -rf /root/.samba/*.rpm
      dnf download samba --source
      mock -r rocky-"$majoros"-x86_64 --enablerepo=devel --define 'dist .el'"$majoros"'_'"$minoros"'.dc' --with dc "$mocksmbver"src.rpm
      cp /var/lib/mock/rocky-"$majoros"-x86_64/result/*.rpm /root/.samba
      createrepo /root/.samba
      dnf update --repofrompath=samba,/root/.samba

      sed -i d /etc/motd

      break
      ;;
   [nN])
      echo ${RED}"Upgrade Cancelled${TEXTRESET}"
      sleep 1
      exit
      ;;
   *) echo invalid response ;;
   esac

done
