#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
  echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat <<EOF
${GREEN}Samba Service Management${TEXTRESET}
${GREEN}Start Samba Service${TEXTRESET}
EOF

systemctl start samba

sleep 1

cat <<EOF
Checking Status

${YELLOW}You can press "q" on the next screen to escape${TEXTRESET}

EOF

sleep 3

systemctl status samba

read -p "Press Any Key"
