#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear
cat  <<EOF
${red}Stopping Samba${textreset} Service
EOF
systemctl stop samba
ps -ax | grep samba | head 
 

cat <<EOF
Checking Status
You can press "q" on the next screen to escape 
EOF

read -p "Pess Any Key" 

systemctl status samba

read -p "Press Any Key"

